# Use root/example as user/password credentials
version: '3.1'

services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27011:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "myRepl" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: localdb
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27012:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "myRepl" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: localdb
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27013:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "myRepl" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: localdb